# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designm2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(850, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(850, 750))
        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(232, 232, 232);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(100, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 150))
        self.label.setBaseSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setFamily("Times")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"image: url(:/newP/1.png);\n"
"")
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setStyleSheet("image: url(:/newP/Результат.png);")
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 180))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setLineWidth(0)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(90)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(33)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.label_8 = QtWidgets.QLabel(self.splitter)
        self.label_8.setObjectName("label_8")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.lcdNumber = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber.setStyleSheet("color: rgb(252, 0, 15);")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Hex)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 3)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_4)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcdNumber_2.setStyleSheet("color: rgb(227, 46, 39);")
        self.lcdNumber_2.setMode(QtWidgets.QLCDNumber.Hex)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("intValue", 4)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.verticalLayout_2.addWidget(self.lcdNumber_2)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.layoutWidget2)
        self.widget_3.setMinimumSize(QtCore.QSize(50, 50))
        self.widget_3.setStyleSheet("image: url(:/newP/g1.png);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setStyleSheet("image: url(:/newP/pddf.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton_2.setStyleSheet("image: url(:/newP/exx.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.table_3 = QtWidgets.QTableWidget(self.splitter_2)
        self.table_3.setEnabled(True)
        self.table_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_3.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"\n"
"")
        self.table_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table_3.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_3.setTextElideMode(QtCore.Qt.ElideRight)
        self.table_3.setShowGrid(True)
        self.table_3.setGridStyle(QtCore.Qt.DashDotLine)
        self.table_3.setWordWrap(True)
        self.table_3.setCornerButtonEnabled(True)
        self.table_3.setObjectName("table_3")
        self.table_3.setColumnCount(1)
        self.table_3.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.table_3.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_3.setHorizontalHeaderItem(0, item)
        self.table_3.horizontalHeader().setCascadingSectionResizes(True)
        self.table_3.horizontalHeader().setDefaultSectionSize(200)
        self.table_3.horizontalHeader().setMinimumSectionSize(22)
        self.table_3.horizontalHeader().setStretchLastSection(True)
        self.table_3.verticalHeader().setCascadingSectionResizes(True)
        self.table_3.verticalHeader().setDefaultSectionSize(45)
        self.table_3.verticalHeader().setMinimumSectionSize(30)
        self.table_3.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStatusTip("")
        self.statusBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionFAQ = QtWidgets.QAction(MainWindow)
        self.actionFAQ.setObjectName("actionFAQ")
        self.actionAbout_Us = QtWidgets.QAction(MainWindow)
        self.actionAbout_Us.setObjectName("actionAbout_Us")
        self.createPDF = QtWidgets.QAction(MainWindow)
        self.createPDF.setObjectName("createPDF")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/New/cat.jpg\"/></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название ЮЛ"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "ИНН ЮЛ"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "ОГРН ЮЛ"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "ФИО ФЛ"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Адрес ЮЛ"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Инфо"))
        self.label_8.setText(_translate("MainWindow", "Участие в судебных делах"))
        self.label_9.setText(_translate("MainWindow", "Истец"))
        self.label_10.setText(_translate("MainWindow", "Ответчик"))
        item = self.table_3.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Участие ФЛ в качестве\n"
"руководителя/учредителя\n"
"в 10 и более ЮЛ"))
        item = self.table_3.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "В составе ЮЛ\n"
"дисквалифицированные лица"))
        item = self.table_3.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Невозможность участия ФЛ \n"
"в организации подтвержден \n"
"в судебном порядке"))
        item = self.table_3.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Количество сотрудников"))
        item = self.table_3.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Недобросовестность поставщика"))
        item = self.table_3.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Налоговая отчетность"))
        item = self.table_3.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Банкротство"))
        item = self.table_3.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "Регистрация в ЕГРЮЛ в пределах \n"
"6 месяцев до момента запроса"))
        item = self.table_3.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "ЮЛ исключено из ЕГРЮЛ"))
        self.statusBar.setProperty("showMessage", _translate("MainWindow", "aaa"))
        self.actionFAQ.setText(_translate("MainWindow", "FAQ"))
        self.actionAbout_Us.setText(_translate("MainWindow", "About Us"))
        self.createPDF.setText(_translate("MainWindow", "createPDF"))

import neww_rc
